name = "createproductworker"
main = "src/index.ts"
compatibility_date = "2022-11-12"

account_id = "c90c277d9089aefac81645bdd3cfe3e2"


[[r2_buckets]]
binding = 'MY_BUCKET' 
bucket_name = 'marketplace-images'
preview_bucket_name =  'marketplace-images'


[vars]
PUBLIC_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5aGJheXFnendyeGFnbHN5cm9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjYyMjIzODUsImV4cCI6MTk4MTc5ODM4NX0.1FhwmmaqDIEWtW5q-gm77TtOy9SdrH2A6ldaGxsUf7k"
MONGO_DB_APP_ID = "application-0-jgbve"
MONGO_DB_API_KEY = "HSUskedJXn9NZmrOyXbiHbdJTpy2YPKVHLNagQdcLL1uB3KlUI4qraiwJ4VcuEBc"
[dev]
port= 5173
